language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"

install: 
  - pip install BitEx
  - python3 setup.py install

# command to run tests
script: 
  - cd tests
  - python -m unittest *.py
branches:
  only:
  - master
  - dev